### ISSUE TITLE
Help doesn't work

### ISSUE THREAD

**Issue by RPrudden** [met-office-lab/dre#11]
At the moment, Modre tries to map utterances like "help" to a stationaryWhenIntent. We must have to reimplement Amazon's intents like the help intent.

<img width="824" alt="screen shot 2016-02-01 at 15 23 26" src="https://cloud.githubusercontent.com/assets/9357195/12721460/d8484b6e-c8f7-11e5-9659-743798efaf06.png">

**Comment by niallrobinson** [comment]
on it

**Comment by RPrudden** [comment]
ok. I had started but was having trouble. see help branch (or don't)
